### ISSUE TITLE
Feature: no,yes

### ISSUE THREAD

**Issue by kylebaron** [metrumresearchgroup/yspec#103]
```yaml
PSURG:
  short: Prior surgery
  values: [0,1]
  decode: ["no", "yes"]
```

```yaml
PSURG:
  short: Prior surgery
  yesno: true
```

**Comment by KatherineKayMRG** [comment]
I like the `yesno: true` short cut - would this return the decode _and_ decode.logical? Also, would we be limited to this only working if it was coded up as 0=no and 1=yes? I know that's fairly standard so no problem is it is, just wondering if we could have an optional 3rd field - so if values are provided, use them in the decoding and if they're not provided the default to 0=no and 1=yes?

```
PSURG:
  short: Prior surgery
  values: [1,2]
  yesno: true
```

Not sure if I've ever needed the decode.logical, I'm usually trying to work out how to get it to show the actual "yes/no" values but I imagine it could be helpful - particularly if someone whats to filter on several logical covariates. I can't think of a reason not to include it.
