### ISSUE TITLE
Titlecase: some first words don't get capitalized

### ISSUE THREAD

**Issue by toddyoder** [metrumresearchgroup/yspec#132]
A short word that would not normally be capitalized in titlecase should be capitalized if it appears at the beginning of a sentence. This example doesn't get handled correctly by yspec.

```yml
FOO:
  short: any first word should be capitalized
```

```r
spec <- yspec::ys_load(here::here("capitalize-me.yml"))
yspec::ys_get_short(spec, title_case = TRUE)
#> $FOO
#> [1] "any First Word Should be Capitalized"
```

**Comment by kylebaron** [comment]
Thanks for the report, @toddyoder .  yspec relies on `tools::toTitleCase` for this conversion and it looks like that's how it is handling your example.  A workaround would be to specify what you want in the spec, either in the base position or in a namespace

```yaml
FOO: 
  short: any first word should be capitalized
  short.cap: Any First Word Should be Capitalized
```


```r
> tools::toTitleCase("any first word should be capitalized")
[1] "any First Word Should be Capitalized"
```
