### ISSUE TITLE
Super Spec

### ISSUE THREAD

**Issue by kylebaron** [metrumresearchgroup/yspec#94]
# Summary
As a user, I want to write different sets of columns into a single yaml file and select which sets to pull in. 

# Tests

**Comment by kylebaron** [comment]
```yaml
SETUP__:
  superspec: true
set1: 
  ETA1: 
    short: ETA-CL
  ETA2:
    short: ETA-V2
set2:
  ETA1: 
    short: ETA-CL
    short: ETA-KA
set3:
  CP:
    short: concentration
  WEEK:
    short: week number
```

This would be loaded with:

```r
spec <- ys_load_get("spec.yml", get = "set1, set3")
```

**Comment by kylebaron** [comment]
All we really need, however, is `short` and maybe `unit`.  What I'm doing now is:


```yaml
SETUP__:
set1:
  ETA1: ETA-CL
  ETA2: ETA-V2
set2:
  ETA1: ETA-CL
  ETA2: ETA-KA

```

The intention isn't fully documented data; but a way to attach a short name to a new column in the data set (like outputs from NONMEM) so this can tap into plotting and summary functions..
